[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_lottery = "B9GiRPwYjU5QkYyAY8wVNcdGE2wLSZ9RUgvskuYiF79t"

[programs.devnet]
solana_lottery = "B9GiRPwYjU5QkYyAY8wVNcdGE2wLSZ9RUgvskuYiF79t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./target/deploy/solana_lottery-devnet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
