[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_lottery = "vurfHgSuomn9PEPK7a4eRjw288n8GaeSwub3pCweKfq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./target/deploy/lottery-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
